[package]
name = "nokheui"
version = "0.1.0"
authors = ["Sangwon Ryu <bdboy090@naver.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
